name: Python Server
run-name: ${{ github.event.head_commit.message }}
on: [push, workflow_dispatch]
concurrency:
  group: "http-server"
  cancel-in-progress: true
jobs:
  # python-server:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v3
  #     - uses: actions/setup-python@v4
  #       with:
  #         python-version: "3.9"
  #     - name: Display Public IP
  #       run: curl https://api.ipify.org
  #     - name: Launch Python Server
  #       run: |
  #         cd ./web
  #         python -m http.server 23456
  ngrok:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # Gist: install ngrok on ubuntu
        #   https://gist.github.com/YamiOdymel/d0337a6be3b2f1297c9eeab6c196fcb7
      - name: Run ngrok
        run: |
          wget -q "https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.tgz"
          tar -xvzf ngrok-v3-stable-linux-amd64.tgz
          pwd
          ls -l
          /home/runner/work/crypto-data/crypto-data/ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
          /home/runner/work/crypto-data/crypto-data/ngrok http 23456
