name: Python Server
run-name: ${{ github.event.head_commit.message }}
on: [push, workflow_dispatch]
concurrency:
  group: "http-server"
  cancel-in-progress: true
jobs:
  http-server:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Display Public IP
        run: curl https://api.ipify.org
      - name: Python Server
        run: |
          cd ./web
          python -m http.server 23456 &
      - name: Run ngrok
        # Gist: install ngrok on ubuntu
        #   https://gist.github.com/YamiOdymel/d0337a6be3b2f1297c9eeab6c196fcb7
        env:
          NGROK_TGZ: ngrok-v3-stable-linux-amd64.tgz
        run: |
          wget -q "https://bin.equinox.io/c/bNyj1mQVY4c/$NGROK_TGZ"
          tar -xvzf $NGROK_TGZ
          pwd
          PATH="$(pwd):$PATH"
          ngrok config add-authtoken ${{ secrets.NGROK_TOKEN }}
          ngrok http 23456
